export const THEMES = {
    divertissement :{
        question : {
            0:  'Dans quel film peut-on entendre la réplique:" Le coeur d\'une  femme est un océan de secrets"?',
            1:  'Que désigne le "Coeur de l\' océan"dans le film Titanic ?',
            2:  "Combien y a-t-il d\' amis principaux dans l' émission de télévision Friends ?",
            3:  "Quel personnage de Friends a abandonné son fiancé au pied de l' autel au tout début de la série ?",
            4:  "Quel superhéros combat le Bouffon vert?",
            5:  "Quel créateur de Spider-man fait une apparition éclair dans le film de 2002 mettant en vedette ce superhéros? ",
            6:  'Quel film de 1978 avait pour slogan: "Vous allez croire qu\' un homme peut voler?',
            7:  'Comment était appelé Superman lorsqu\'il n\' était q\' un bébé sur la planète Krypton?',
            8:  'A l\' origine, que représente "La Panthère rose" dans les films mettant en vedette Peter Sellers?',
            9:  'Quel est le nom de trois lettres de la ligne de vêtements de Jennifer Lopez?',
            10: 'De quelle couleur est Shrek?',
            11: 'Quel animal est le meilleur ami de Shrek?',
            12: 'Quel est le titre complet du deuxième film des Pirates des Caraïbes?',
            13: 'Que tient Johnny Depp dans sa main sur l\'affiche publicitaire du film Pirates des Caraïbes :Le coffre du mort?',
            14: 'Quel superhéros est aussi connu sous lenom de Bruce Wayne?',
            
        },
        reponse : {
            0:  ["Titanic","N' oublie jamais","Eternal Sunshine","Nos étoiles contraires"],
            1:  ["Un diamant","Un or","Une argent","Un saphir"],
            2:  ["Six","Cinq","Sept","Quatre"],
            3:  ["Rachel Green","Ross Geller","Monica Geller","Phoebe Buffay"],
            4:  ["Spider-man","Superman","Batman","Flash"],
            5:  ["Stan Lee","Andrew Adamson","Tex Avery","Ralph Bakshi"],
            6:  ["Superman","Green Lantern","Aquaman","Batman"],
            7:  ["Kal-El","Jonathan Kent","Jor-El","Clark Kent"],
            8:  ["Un diamant ","Une Panthère","Une livre","Un bijou"],
            9:  ["JLo","BTi","RXa","PLos"],
            10: ["Vert","Bleue","Violet","Noire"],
            11: ["L'âne","Le chat","Le Dragon","L'oie"],
            12: ["Le coffre du mort","La malédiction de BlackPearl","La fontaine de Jouvence","La Vengeance de Salazar"],
            13: ["Un pistolet","Une épée","Un chapeau","Une carte"],
            14: ["Batman","Superman","Aquaman","Flash"],

  
        }
    },
    Geographie:{
        question: {
            0:  'Quelle montagne est appelée Sagarmatha au Népal c\'est-à-dire "Le front du ciel"?',
            1:  'Parmi les 10 plus hautes montagnes du monde,combien se trouvent en Asie?',
            2:  'Quelle planète posséderait la plus haute montagne du système solaire?',
            3:  'Quel désert entoure LasVegas?',
            4:  'Quel personnage dans Christian Andersen est assis sur le bord de l\'eau à Copenhague?',
            5:  'Quel jeu de construction est le thème d\'un parc d\'attractions danois?',
            6:  'De quelle couleur est larox du drapeau finlandais?',
            7:  'Quel produit a déjà été extrait à Salzbourg?',
            8:  'Quelle est la capitale de la Tunisie?',
            9:  'Quel produit correspond à environ 75% des exportations islandaises?',
            10: 'En Islande,qu\'est-ce qui était interrompu pendant le mois de juillet et ce jusqu \'en 1983 et tous les jeudis jusqu\'en 1987?',
            11: 'Quel corps céleste apparaît dans le triangle blanc du drapeau du Djibouti?',
            12: 'Quelle est la principale religion au Djibouti?',
            13: 'Quel pays d\'Amérique du Sud porte le nom de Christophe Colomb?',
            14: 'Qu\'a-t-on aboli en Colombie en 1849?',           
        },
        reponse : {
            0:  ["L'Everest","Les Alpes","Les Pyrénées","Les Vosges"],
            1:  ["10","1","5","7"],
            2:  ["Mars","Jupiter","Venus","Terre"],
            3:  ["Le désert des Mojaves","Le désert d'Arabie","Le désert de Gobi","Le désert de Patagonie"],
            4:  ["La petite sirène","Fantasia","La Belle et le Clochard","L'étrange Noël de monsieur Jack"],
            5:  ["Lego","UNO","Monopoly","Cartes"],
            6:  ["Bleue","Rouge","Noire","Grenat"],
            7:  ["Le sel","Le sucre","Le poivre","Le curcuma"],
            8:  ["Tunis","Paris","Antananarivo","Tokyo"],
            9:  ["Le poisson","La vanille","Le riz","Le cacao"],
            10: ["La télévision","La radio","Le téléphone","L'ordinateur"],
            11: ["Une étoile","Un soleil","Une Lune","Un astre"],
            12: ["L'islam","Le christianisme","Le Bouddhisme","Le taoïsme"],
            13: ["La colombie","L'Argentine","L'Uruguay","Le Brésil"],
            14: ["L'esclavage","La colonisation","La peine de mort","Le racisme"],
        }
    },
    sciences:{
        question:{
            0:"Qu'est ce qu'un ichtiologiste étudie?",
            1:"Comment s'appelle le petit du cheval?",
            2:"Quel est le plus grand dinosaure découvert jusqu'à maintenant?",
            3:"Quelle fruit est cultivée dans le plus grand nombre de pays?",
            4:"Quelle entreprise informatique a commercialisé la série des PowerBook en 1991",
            5:"Quel est le métal le plus abondant sur notre planète",
            6:"Quel élément porte le numéro atomique 26?",
            7:"Quelle organe produit l'urine?",
            8:"Quel élément Jost Burgi a-t-il ajouté à une horloge en 1577, ce qui a permis de préciser le décompte de l'heure?",
            9:"Quel est le nom de l'étoile la plus proche de la terre?",
            10:"Quel gaz constitue environ 74% de la masse du soleil?",
            11:"Que craint une personne gymnophobe?",
            12:"Combien de lune la planete Mars possède-t-elle?",
            13:"Quel est le seul continent où il n'y apas d'abeilles?",
            14:"Quel élément Pierre et Marie ont-ils découvert en 1898?",
            //15:"Quel est le nom du premier satellite artificiel de la Terre?",
        },
        reponse:{
            0:["Les poissons","Les insectes","Les champignons","Les végétaux"],
            1:["Le poulain","Le tétard","Le faon","Le chamelon"],
            2:["Brachiosaure","Tyrannosaure","Vélociraptor","Titanosaure"],
            3:["Banane","Fraise","Cerise","Mangue"],
            4:["Apple Inc","Samsung","Huawei","Xiaomi"],
            5:["Fer","Aluminium","Cuivre","Nickel"],
            6:["Le carbone","L'hélium","Le magnesium","Le silicium"],
            7:["Le rein","L'urètre","La vessie","Le prostate"],
            8:["L'aiguille des minutes","L'aiguille des secondes","Une pile","Un régulateur"],
            9:["Soleil","Proxima Centauri","Alpha centauri","Barnard's Star"],
            10:["Hydrogène","Butane","Méthane","Helium"],
            11:["La nudité","La gymnastique","Des espaces ouverts et des lieux publics","Les piqures"],
            12:["Deux","Une","Trois","Quatre"],
            13:["L'Antarctique","L'Asie","L'Afrique","L'Europe"],
            14:["Le radium","Le potassium","Le Magnesium","Le plutonium"],
            //15:["Sputnik I","Explorer I","Mir","TerreStar"],
        }
    },
    litterature:{
        question:{
            0:"Quelle livre de Shakespear raconte l'histoire de Mlle Capulet qui tombe amoureuse de M, Montaigu?",
            1:"Quel personnage de comédie musical est porté par le vent d'est avec son parapmuie et sa valise?",
            2:"Quelle statue réalisée par le sculteur Frédéric Auguste Bartholdi est la plus célàbre de New York?",
            3:"Qui a peint Mona Lisa?",
            4:"Si ma petite vache a mal aux pattes, que doit-on tirer pour qu'elle aille bien mieux?",
            5:"Que fait-on Sur le pont d'Avignon?",
            6:"De quel instrument joue Sherlock Holmes dans ses moments de détentes?",
            7:"Combien de cordes possède un violon Standard?",
            8:"Comment s'appelle l'enfant dans 'Le livre de la jungle'?",
            9:"Quel auteur est surnommé 'Le barde'?",
            10:"Quel personnage de conte de fées avait deux demi-soeurs fort déplaisantes",
            11:"Quel personnage de dessin animé a fait ses débuts en 1928 avec sa campagne Minnie das le film Steamboat Willie?",
            12:"Entre quelles parties du corps place-t-on généralement le bongos?",
            13:"De quelle nationalité est Paul Cézanne?",
            14:"A quelle heure Cendrillon doit-elle quitter le bal?",
        },
        reponse:{
            0:["Roméo et Juliette","Bonnie et Clyde","Orphée et Eurydice","Pyrame et Thisbé"],
            1:["Marry Poppins","Michael Banks","Bert","Oncle Albert"],
            2:["Statue de la liberté","Statue de Lafayette","Satue de Vaubon","Statue de Champollion"],
            3:["Léonard de Vinci","Michel-Ange","Rembrandt","Van Gogh"],
            4:["La queue","Les oreilles","La langue","Ses pattes"],
            5:["On y danse","On y chante","On prend l'air","On pèche"],
            6:["Du violon","De l'harmonica","De la guitare","De la flute"],
            7:["Quatre","Deux","Trois","Six"],
            8:["Mowgli","Bagheera","Baloo","Shere Kan"],
            9:["William Shakespeare","Pierre Corneille","Molière","Pierre Corneille"],
            10:["Cendrillon","Aurore","Pocahontas","Jasmine"],
            11:["Mickey Mouse","Donald","Pluto","Patt"],
            12:["Entre les genoux","Entre les jambes","Entre les jambes","Entre le bras et la poitrine"],
            13:["Français","Anglais","Africain","Chinois"],
            14:["12h","01h","12h30","01h30"],
        }
    },
    histoire : {
        question : {
            0 : "Où l\'homme devrait-il poser le pied avant la fin de la décennie, selon un discours de John Kennedy prononcé en 1961 ?",
            1 : "Qui a été le premier Américain à voyager dans l\'espace ?",
            2 : "De quel pays proviennent les astronautes que l\'on surnomme les \"taïkonautes\" depuis 1998",
            3 : "Quel astronaute et vétéran américain a voyagé dans l\'espace à l\'âge de 77 ans ?",
            4 : "Qui fut le premier astronaute britannique ?",
            5 : "Qu\'a fait Youri Gagarine après être descendu de l\'autobus qui le menait à la navette spatiale lors de sa première mission dans l\'espace ?",
            6 : "Qui a été le premier président catholique des Etats-Unis ?",
            7 : "Qui a été le premier président des Etats-Unis né au 20ème siècle ?",
            8 : "Quelle reine britannique a offert un bureau au gouvernement américain que personne n\'a utilisé jusqu\'à la présidence de John F.Kennedy ?",
            9 : "Qui a été le premier président des Etats-Unis à tenir une conférence de presse télévisée ?",
            10 : "Quel est le seul président des Etats-Unis à avoir offert à son frère un poste important dans son administration ?",
            11 : "Quel sommet avait été conquis par 1919 personnes à la fin de 2003 ?",
            12 : "Qui a répondu \"Parce qu\'il est là\" quand on lui a demandé pourquoi il voulait escalader le mont Everst ?",
            13 : "Qui était le chef du groupe d\'alpinistes ayant escaladé avec succès l\'Everest en 1953 ?",
            14 : "En quelle année l\'ISPM a été fondé ?"
        },
        reponse : {
            0 : ["Sur la lune","Sur la planète Mars","Sur la planète Jupiter","Sur une météorite"],
            1 : ["Alan Shepard","Edward Kenway","Duncan Walpole","Spohie Adenot"],
            2 : ["De la Chine","De la Suisse","De France","Du Vietnam"],
            3 : ["John Glenn","Daniel Burbank","Eileen Collins","McClain"],
            4 : ["Helen Sharman","Timothy Peake","Hamish Harding","Michael Foale"],
            5 : ["Il a uriné sur une roue de l\'autobus","Il est allé au bar","Il s\'est endormi dans sa baignoire","Il a regardé un film"],
            6 : ["John F.Kennedy","Joe Biden","Bill Clinton","Jimmy Carter"],
            7 : ["John F.Kennedy","Barack Obama","Gerald Ford","Donald Trump"],
            8 : ["Reine Victoria","Édouard VII","Élisabeth II","Guillaume IV"],
            9 : ["John F.Kennedy","Joe Biden","Barack Obama","Donald Trump"],
            10 : ["John F.Kennedy","George W. Bush","Richard Nixon","Franklin D. Roosevelt"],
            11 : ["Mont Everest","Mont Blanc","Mont Viso","Pointe Dufour"],
            12 : ["George Mallory","Jordan Romero","Hillary","Norgay"],
            13 : ["John Hunt","Edmund Hillary","Tenzing Norgay","Reinhold Messner"],
            14 : ["1993","2003","1998","2012"]
        }
    },
    sports : {
        question : {
            0 : "Quelle équipe de baseball a remporté la série mondiale le plus grand nombre de fois ?",
            1 : "Dans quelle ville jouait l\'équipe historique de la ligue majeure de baseball, aussi nommée les Trolley Dodgers ?",
            2 : "Quel joueur des Yankees de New York a obtenu le plus grand nombre de présences officielles au bâton et de coups sûrs durant les séries mondiales ?",
            3 : "Quelle ère du baseball, marquée par des scores faibles, s'est terminée par l\'interdiction de la balle mouillée et l\'adoption de la balle rapide ?",
            4 : "Combien d\'équipes actuelles de la ligue majeure de baseball n\'ont jamais remporté la série mondiale ?",
            5 : "Qui était le receveur du match lorsque Don Larsen a lancé la seule partie parfaite de l\'histoire de la série mondiale ?" ,
            6 : "Quel buisson à fleurs épineux doit être habillé chaque printemps afin de produire de belles fleurs ?",
            7 : "Qu\'ont en commun la kalmie à larges feuilles, la cléùatite du père Armand, la vigne commune et le jasmin-trompette ?",
            8 : "Quelle peste a dévasté vos dahlias si vous y observez une traînée visqueuse ?",
            9 : "Quel légume appelle-t-on parfois un zucchini ?",
            10 : "De quel continent provient la tomate rouge ?",
            11 : "Quel Etat américain produit le plus de pommes de terre après l\'Idaho ?",
            12 : "Que doit attendre un lanceur de disque avant de sortir de la zone de lancer ?",
            13 : "Quel quart-arrière des Steelers de Pittsburgh a établi un record national de lancer du javelot au collégial ?",
            14 : "Quelle épreuve olympique possède deux styles: le lancer avec élan classique et le lancer avec élan en rotation ?"
        },
        reponse : {
            0 : ["Les Yankees de New York"," Astros de Houston","Est. Baltimore","Ouest. Angels L.A. Angels"],
            1 : ["Brooklyn","New York","Denver","Miami"],
            2 : ["Yogi Berra","DJ LeMahieu","Aaron Judge","Giovanny Urshela"],
            3 : ["L\'ère de la balle morte","l\'ère de la balle","l\'ère du bâton","l\ère du lanceur"],
            4 : ["8","7","5","2"],
            5 : ["Yogi Berra","Yadier Molina","Bengie Molina","José Molina"],
            6 : ["Le Rosier","Les Pommiers d'ornement","Le Corylopsis","Les Magnolias"],
            7 : ["Plantes grimpantes","Bignone","Campsis","azote"],
            8 : ["Escargots","Limace","Papillon","Chenille"],
            9 : ["Courgette","Tomate","Aricot Vert","Carotte"],
            10 : ["L\'Amérique du Sud","Europe","Afrique","Asie"],
            11 : ["Washington","Indiana","Philadelphie","San Francisco"],
            12 : ["Il doit attendre que le disque retombe sur le terrain","Il doit attendre quelqu'un","Il ne doit jamais attendre","Il doit attendre le receveur"],
            13 : ["Terry Bradshaw","Kenny Pickett","Mitchell Trubisky","Mason Rudolph"],
            14 : ["Le lancer du poids","Lancer de javelot","lancer de disque","lancer de marteau"]
        }
    }
}